[package]
name = "tlc-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "tlc"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-opentelemetry.workspace = true

tlc-util = { path = "../util" }
tlc-engine = { path = "../engine" }
tlc-checkpoint = { path = "../checkpoint" }
tlc-telemetry = { path = "../telemetry" }
tlc-progress = { path = "../progress" }
