[package]
name = "tlc-engine"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
crossbeam.workspace = true
rayon.workspace = true
thiserror.workspace = true
tracing.workspace = true

tlc-util = { path = "../util" }
tlc-checkpoint = { path = "../checkpoint" }
tlc-progress = { path = "../progress" }
ulid.workspace = true

[dev-dependencies]
blake3.workspace = true
tempfile.workspace = true
uuid.workspace = true
tracing-subscriber.workspace = true
criterion.workspace = true

[[bench]]
name = "engine_scaling"
harness = false
